# Generated by Django 5.1.6 on 2025-02-14 03:08

import files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_uploaded_by_delete_fileshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=files.models.user_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'owner', 'parent_folder')},
        ),
    ]
