# Generated by Django 5.1.6 on 2025-02-16 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_file_file_alter_folder_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
